// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars final
Map<String, dynamic> environment = {
  "appConfig": "lib/config/config_en.json",

  /// ➡️ lib/common/config.dart
  "serverConfig": {
    'type': 'woo',
    'url': 'https://octaeg.com/',
    'consumerKey': 'ck_88fa7311c9a625bed0cdf21c249c4b8d4db41dac',
    'consumerSecret': 'cs_b32c4cfcaffa24965713ab2e07fa74d3d4eaf03d',
    'blog':
    'https://allneeds4u/', //Your website woocommerce. You can remove this line if it same url
    /// remove to use as native screen
    'forgetPassword': 'https://octaeg.com/wp-login.php?action=lostpassword'
  },
  "defaultDarkTheme":false,
  "loginSMSConstants":{
    "countryCodeDefault":"EG",
    "dialCodeDefault":"+20",
    "nameDefault":"مصر‎"
  },
  "storeIdentifier":{
    "disable":true,
    "android":"com.souqocta.www",
    "ios":"1469772800"
  },
  "advanceConfig":{
    "DefaultLanguage":"en",
    "DetailedBlogLayout":"halfSizeImageType",
    "EnablePointReward":true,
    "hideOutOfStock":false,
    "EnableRating":true,
    "hideEmptyProductListRating":true,
    "EnableSkuSearch":true,
    "showStockStatus":true,
    "GridCount":3,
    "isCaching":true,
    "kIsResizeImage":false,
    "DefaultCurrency":{
      "symbol":"LE",
      "decimalDigits":2,
      "symbolBeforeTheNumber":true,
      "currency":"USD",
      "currencyCode":"usd",
      "smallestUnitRate":100
    },
    "Currencies":[
      {
        "symbol":"LE",
        "decimalDigits":2,
        "symbolBeforeTheNumber":true,
        "currency":"USD",
        "currencyCode":"usd",
        "smallestUnitRate":100
      }
    ],
    "DefaultStoreViewCode":"",
    "EnableAttributesConfigurableProduct":["color",
      "size"],
    "EnableAttributesLabelConfigurableProduct":["color",
      "size"],
    "isMultiLanguages":true,
    "EnableApprovedReview":false,
    "EnableSyncCartFromWebsite":false,
    "EnableSyncCartToWebsite":false,
    "EnableShoppingCart":false,
    "EnableFirebase":false,
    "RatioProductImage":1.2,
    "EnableCouponCode":true,
    "ShowCouponList":true,
    "ShowAllCoupons":true,
    "ShowExpiredCoupons":true,
    "AlwaysShowTabBar":false,
    "PrivacyPoliciesPageId":25569,
    "QueryRadiusDistance":10,
    "AutoDetectLanguage":false
  },
  "defaultDrawer":{
    "logo":"assets/images/slogo.png",
    "background":null,
    "items":[
      {
        "type":"home",
        "show":true
      },
      {
        "type":"blog",
        "show":false
      },
      {
        "type":"categories",
        "show":true
      },
      {
        "type":"cart",
        "show":true
      },
      {
        "type":"profile",
        "show":true
      },
      {
        "type":"login",
        "show":true
      },
      {
        "type":"category",
        "show":true
      }
    ]
  },
  "defaultSettings":[
    "wishlist",
    "wallet",
    "notifications",
    "language",
    "darkTheme",
    "order",
    "point",
    "rating"
],
  "loginSetting":{
    "IsRequiredLogin":false,
    "showAppleLogin":false,
    "showFacebook":false,
    "showSMSLogin":true,
    "showGoogleLogin":true,
    "showPhoneNumberWhenRegister":false,
    "requirePhoneNumberWhenRegister":false
  },
  "oneSignalKey":{
    "enable":false,
    "appID":"8b45b6db-7421-45e1-85aa-75e597f62714"
  },
  "onBoardingData":[
    {
      "title":"Welcome to  Octa",
      "desc":" Octa is on the way to serve you. ",
      "image":"assets/images/sfogg-delivery-1.png"
    },
    {
      "title":"Connect Surrounding World",
      "image":"assets/images/fogg-uploading-1.png",
      "desc":"See all things happening around you just by a click in your phone. Fast, convenient and clean."
    },
    {
      "title":"Let's Get Started",
      "image":"fogg-order-completed.png",
      "desc":"Waiting no more, let's see what we get!"
    }
  ],
  "adConfig":{
    "enable":false,
    "facebookTestingId":"",
    "googleTestingId":[],
    "ads":[
      {
        "type":"banner",
        "provider":"google",
        "iosId":"ca-app-pub-3940256099942544/2934735716",
        "androidId":"ca-app-pub-3940256099942544/6300978111",
        "showOnScreens":["home",
          "search"],
        "waitingTimeToDisplay":2
      },
      {
        "type":"banner",
        "provider":"google",
        "iosId":"ca-app-pub-2101182411274198/5418791562",
        "androidId":"ca-app-pub-2101182411274198/4052745095"
      },
      {
        "type":"interstitial",
        "provider":"google",
        "iosId":"ca-app-pub-3940256099942544/4411468910",
        "androidId":"ca-app-pub-3940256099942544/4411468910",
        "showOnScreens":["profile"],
        "waitingTimeToDisplay":5
      },
      {
        "type":"reward",
        "provider":"google",
        "iosId":"ca-app-pub-3940256099942544/1712485313",
        "androidId":"ca-app-pub-3940256099942544/4411468910",
        "showOnScreens":["cart"]
      },
      {
        "type":"banner",
        "provider":"facebook",
        "iosId":"IMG_16_9_APP_INSTALL#430258564493822_876131259906548",
        "androidId":"IMG_16_9_APP_INSTALL#430258564493822_489007588618919",
        "showOnScreens":["home"]
      },
      {
        "type":"interstitial",
        "provider":"facebook",
        "iosId":"430258564493822_489092398610438",
        "androidId":"IMG_16_9_APP_INSTALL#430258564493822_489092398610438"
      }
    ]
  },
  "firebaseDynamicLinkConfig":{
    "isEnabled":true,
    "uriPrefix":"https://fluxstoreinspireui.page.link",
    "link":"https://mstore.io/",
    "androidPackageName":"com.souqocta.www",
    "androidAppMinimumVersion":1,
    "iOSBundleId":"com.inspireui.mstore.flutter",
    "iOSAppMinimumVersion":"1.0.1",
    "iOSAppStoreId":"1469772800"
  },
  "languagesInfo":[
    {
      "name":"English",
      "icon":"assets/images/country/gb.png",
      "code":"en",
      "text":"English",
      "storeViewCode":""
    }
  ],
  "unsupportedLanguages":["ku"],
  "paymentConfig":{
    "DefaultCountryISOCode":"EG",
    "DefaultStateISOCode":"EG",
    "EnableShipping":true,
    "EnableAddress":true,
    "EnableCustomerNote":true,
    "EnableAddressLocationNote":false,
    "EnableAlphanumericZipCode":false,
    "EnableReview":true,
    "allowSearchingAddress":true,
    "GuestCheckout":true,
    "EnableOnePageCheckout":false,
    "NativeOnePageCheckout":false,
    "CheckoutPageSlug":{
      "en":"checkout"
    },
    "EnableCreditCard":false,
    "UpdateOrderStatus":false,
    "ShowOrderNotes":true,
    "EnableRefundCancel":true,
    "GoogleApiKey":""
  },
  "payments":{
    "paypal":"assets/icons/payment/paypal.png",
    "stripe":"assets/icons/payment/stripe.png",
    "razorpay":"assets/icons/payment/razorpay.png",
    "tap":"assets/icons/payment/tap.png"
  },
  "stripeConfig":{
    "serverEndpoint":"https://stripe-server.vercel.app",
    "publishableKey":"pk_test_MOl5vYzj1GiFnRsqpAIHxZJl",
    "enabled":true,
    "paymentMethodId":"stripe",
    "returnUrl":"fluxstore://inspireui.com",
    "enableManualCapture":false
  },
  "paypalConfig":{
    "clientId":"ASlpjFreiGp3gggRKo6YzXMyGM6-NwndBAQ707k6z3-WkSSMTPDfEFmNmky6dBX00lik8wKdToWiJj5w",
    "secret":"ECbFREri7NFj64FI_9WzS6A0Az2DqNLrVokBo0ZBu4enHZKMKOvX45v9Y1NBPKFr6QJv2KaSp5vk5A1G",
    "production":false,
    "paymentMethodId":"paypal",
    "enabled":true
  },
  "razorpayConfig":{
    "keyId":"rzp_test_SDo2WKBNQXDk5Y",
    "keySecret":"RrgfT3oxbJdaeHSzvuzaJRZf",
    "paymentMethodId":"razorpay",
    "enabled":true
  },
  "tapConfig":{
    "SecretKey":"sk_test_XKokBfNWv6FIYuTMg5sLPjhJ",
    "paymentMethodId":"tap",
    "enabled":true
  },
  "mercadoPagoConfig":{
    "accessToken":"TEST-5726912977510261-102413-65873095dc5b0a877969b7f6ffcceee4-613803978",
    "production":false,
    "paymentMethodId":"woo-mercado-pago-basic",
    "enabled":true
  },
  "defaultCountryShipping":[],
  "afterShip":{
    "api":"e2e9bae8-ee39-46a9-a084-781d0139274f",
    "tracking_url":"https://fluxstore.aftership.com"
  },
  "productDetail":{
    "height":0.4,
    "marginTop":0,
    "safeArea":false,
    "showVideo":true,
    "showBrand":true,
    "showThumbnailAtLeast":1,
    "layout":"simpleType",
    "borderRadius":3.0,
    "ShowSelectedImageVariant":true,
    "ForceWhiteBackground":false,
    "AutoSelectFirstAttribute":true,
    "enableReview":true,
    "attributeImagesSize":50.0,
    "showSku":true,
    "showStockQuantity":true,
    "showProductCategories":true,
    "showProductTags":true,
    "hideInvalidAttributes":false,
    "showQuantityInList":false,
    "productListItemHeight":125
  },
  "blogDetail":{
    "showComment":true,
    "showHeart":true,
    "showSharing":true,
    "showTextAdjustment":true,
    "enableAudioSupport":false
  },
  "productVariantLayout":{
    "color":"color",
    "size":"box",
    "height":"option",
    "color-image":"image"
  },
  "productAddons":{
    "allowImageType":true,
    "allowVideoType":true,
    "allowCustomType":true,
    "allowedCustomType":["png",
      "pdf",
      "docx"],
    "allowMultiple":false,
    "fileUploadSizeLimit":5.0
  },
  "cartDetail":{
    "minAllowTotalCartValue":0,
    "maxAllowQuantity":10
  },
  "productVariantLanguage":{
    "en":{
      "color":"Color",
      "size":"Size",
      "height":"Height",
      "color-image":"Color"
    },
    "ar":{
      "color":"اللون",
      "size":"بحجم",
      "height":"ارتفاع",
      "color-image":"اللون"
    },
    "vi":{
      "color":"Màu",
      "size":"Kích thước",
      "height":"Chiều Cao",
      "color-image":"Màu"}
  },
  "excludedCategory":311,
  "saleOffProduct":{
    "ShowCountDown":true,
    "HideEmptySaleOffLayout":false,
    "Color":"#C7222B"
  },
  "notStrictVisibleVariant":true,
  "configChat":{
    "EnableSmartChat":true,
    "showOnScreens":["profile"],
    "version":2,
    "hideOnScreens":[]
  },
  "smartChat":[
    {
      "app":"https://wa.me/+201014555588",
      "iconData":"whatsapp"
    },
    {
      "app":"tel:01014555588",
      "iconData":"phone"
    },
    {
      "app":"sms://01014555588",
      "iconData":"sms"
    },
    {
      "app":"https://urlgeni.us/facebook/kWvt",
      "iconData":"facebookMessenger"
    }
  ],
  "deliveryConfig":{
    "DisableDeliveryManagement":false
  },
  "loadingIcon":{
    "type":"ripple",
    "size":30.0
  },
  "splashScreen":{
    "enable":true,
    "duration":2000,
    "type":"rive",
    "image":"assets/images/splashscreen.riv",
    "animationName":"fluxstore",
    "boxFit": "cover",
    "backgroundColor": "#000000",
  },
  "darkConfig":{
    "MainColor":"#3FC1BE"
  },
  "lightConfig":{
    "MainColor":"ffff9800"}};